#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q *@@bio
#$ -N bowtie_Mfasc_Olf2T2	 # Specify job name
#$ -pe smp 8            #cores


module load bio        # Required modules to load

bowtie2 -x /scratch365/crivaldi/data/M_fascicularis/M_fasc_Olf2T2 -U /scratch365/crivaldi/data/2014_saliva/Preliminary_Saliva_RAD_Data/Barcode_CTGCGAATT.fastq -S /scratch365/crivaldi/data/M_fascicularis/Mfasc_Olf2T2.sam


##script to aln RAD reads cut with trimmer.py and cutadapt to Mfasc genome
##sequences sorted with radtrimmer.py
