#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long
#$ -N bowtie_prev	 # Specify job name
#$ -pe smp 8            #cores


module load bio        # Required modules to load

bowtie2 -x /scratch365/crivaldi/data/Prevotella/Prevatella_bowtie_index/Pint_bowtie -U /afs/crc.nd.edu/user/c/crivaldi/data/_AS0710/AS0710.cut.fq -S /afs/crc.nd.edu/user/c/crivaldi/data/_AS0710/AS0710_cut_Prev_bowtie.sam


##script to aln RAD reads cut with trimmer.py and cutadapt to Mfasc genome
##sequences sorted with radtrimmer.py
