#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N BWAindexbuild	         # Specify job name

module load bio	         # Required modules


set path = ( $path /afs/crc.nd.edu/user/c/crivaldi/local/bin )
cd  /afs/crc.nd.edu/user/c/crivaldi/data


bwa index -a bwtsw /scratch365/crivaldi/data/M_fascicularis/GCF_000364345.1_Macaca_fascicularis_5.0_genomic.fna


