#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N BWAP_know	         # Specify job name
#$ -r y			#don't know what this does-in sheri's job scripts
#$ -pe smp 8		#cores

module load bio	         # Required modules

set path = ( $path /afs/crc.nd.edu/user/c/crivaldi/local/bin )

cd  /afs/crc.nd.edu/user/c/crivaldi/data

###BWA INDEX STEP
###bwa index -a bwtsw /scratch365/crivaldi/data/M_fascicularis/GCF_000364345.1_Macaca_fascicularis_5.0_genomic.fna

###BWA ALIGNMENT STEP


   bwa aln -n 3 -k 8 -t 8 /scratch365/crivaldi/data/P_knowlesi/GCF_000006355.1_ASM635v1_genomic.fna /afs/crc.nd.edu/user/c/crivaldi/local/bin/NDBL_HOT_RAD/python/RAD_NoIndex_L002_R1_all.trimmed.fq > /scratch365/crivaldi/data/P_knowlesi/P_knowlesi.sai


###BWA ALIGNMENT STEP IF USING PAIRED READS


####for paired ends###   bwa aln -n 3 -k 8 -t 8 Daphnia_magna_v2.4.fasta CombinedMagnaQC_2.fq > Magna_PE2redone.sai


###BWA SAMSE STEP (SAMPE for paired ends)



   bwa samse /scratch365/crivaldi/data/P_knowlesi/GCF_000006355.1_ASM635v1_genomic.fna /scratch365/crivaldi/data/P_knowlesi/P_knowlesi.sai /afs/crc.nd.edu/user/c/crivaldi/local/bin/NDBL_HOT_RAD/python/RAD_NoIndex_L002_R1_all.trimmed.fq > /scratch365/crivaldi/data/P_knowlesi/P_knowlesi.sam

 



####ben script from radwiki ### Magna_PE1redone.sai Magna_PE2redone.sai CombinedMagnaQC_1.fq CombinedMagnaQC_2.fq > MagnaBothLanesredone.sam
