#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N fastqc_R1_all	         # Specify job name

module load bio	         # Required modules
module load python/3.4.0


cd /scratch365/crivaldi/data/Reads/

fastqc /scratch365/crivaldi/data/Reads/RAD_NoIndex_L002_R1_all.fastq -o /scratch365/crivaldi/data/fastqc_out_2_29_RADseq/

