#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -pe mpi-12 12	 # Specify parallel environment and legal core size
#$ -q long		 # Specify queue
#$ -N	grep_shot	         # Specify job name

module load bio        # Required modules to load

egrep -i "aacgccaa" $SCRATCH/data/Reads/RAD_NoIndex_L002_R1_all.fastq > $SCRATCH/data/Reads/grepshot.txt # Application to execute
