#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long
#$ -N clusterblast	 # Specify job name
#$ -pe smp 8            #cores


module load bio        # Required modules to load


/afs/crc.nd.edu/user/c/crivaldi/local/bin/blastn -query /afs/crc.nd.edu/user/c/crivaldi/data/_AS0710/ASO710_hmmout_cluster_95.centroids -db /scratch365/crivaldi/data/blast_db_nt/nt -num_threads 8 -max_target_seqs 10 -evalue 10e6 -outfmt 6 -out /afs/crc.nd.edu/user/c/crivaldi/Classes/AS0710_hmmout_cluster95.outfmt6


##this script blasts the output of hmmersearch (using an 18s apicomplexan alignment to build profile)  and vsearch (from mothur package) clustering(@95% similarity) against a local version of the NCBI nr database (all nucleotide sequences)

