#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long # Specify queue
#$ -N	make_R1_db	         # Specify job name

module load bio        # Required modules to load


/afs/crc.nd.edu/user/c/crivaldi/local/bin/makeblastdb -in /afs/crc.nd.edu/group/hollocher/macaque/Run121815B_KlegarthRAD_ReRun/Sample_RAD/fastq_only/all_combined/Rad_NoIndex_L002_R1.fasta -dbtype nucl -out /afs/crc.nd.edu/user/c/crivaldi/data/RAD_R1db





