#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N muscle_Ors_4	         # Specify job name
#$ -pe smp 8 		#cores


module load bio	         # Required modules

cd /afs/crc.nd.edu/user/c/crivaldi/local/bin/

./muscle3.8.31_i86linux64 -in ~/data/zsyed/Ors_4.fas -out ~/data/zsyed/Ors_4.aln

