#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N muscle_co1	         # Specify job name

module load bio	         # Required modules

cd /afs/crc.nd.edu/user/c/crivaldi/local/bin/

./muscle3.8.31_i86linux64 -in /scratch365/crivaldi/data/amy1.fasta -out /scratch365/crivaldi/data/amy1.aln

