#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N parallelparser_1	         # Specify job name

module load bio	         # Required modules
module load python/3.4.0

cd /scratch365/crivaldi/

python3 /scratch365/crivaldi/scripts/ParallelParser.py /scratch365/crivaldi/RAD_NoIndex_L002.spec


