#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N RADtrimmer_blood	 # Specify job name
#$ -pe smp 8             #cores

module load bio	         # Required modules


set path = ( $path /afs/crc.nd.edu/user/c/crivaldi/local/bin )
python  /afs/crc.nd.edu/user/c/crivaldi/local/bin/NDBL_HOT_RAD/python/radtag0_trimmer.py -i /afs/crc.nd.edu/user/c/crivaldi/data/2012_RAD_BARCODES_BLOOD.txt /afs/crc.nd.edu/user/c/crivaldi/data/HotRad_out/2012/2012_blood.fastq


