#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N RADtrimmer	         # Specify job name

module load bio	         # Required modules


set path = ( $path /afs/crc.nd.edu/user/c/crivaldi/local/bin )
python  /afs/crc.nd.edu/user/c/crivaldi/local/bin/NDBL_HOT_RAD/python/radtag0_trimmer.py -i /afs/crc.nd.edu/user/c/crivaldi/data/HotRad_out/RAD_BARCODES.txt /afs/crc.nd.edu/user/c/crivaldi/data/cutadapt_out/RAD_R1_cut_Msel1-2_aln.fastq


