#!/bin/csh

#$ -M crivaldi@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q long		 # Specify queue
#$ -N muscle_Mfasccluster	         # Specify job name
#$ -pe smp 8 		#cores


module load bio	         # Required modules

cd /afs/crc.nd.edu/user/c/crivaldi/local/bin/



./muscle3.8.31_i86linux64 -in /scratch365/crivaldi/data/2014_saliva/Preliminary_Saliva_RAD_Data/bowtie_out/Barcode_G_M_fasc_fromsam.centroids -out /scratch365/crivaldi/data/2014_saliva/Preliminary_Saliva_RAD_Data/bowtie_out/M_fasc_centroids.aln



